# Generated by Django 4.1.4 on 2022-12-29 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0002_alter_product_options_alter_stock_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockproduct',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stockproduct',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
